study3 <- function(start_con = 1, end_con = 10, start_rep = 1, end_rep = 20) {
  library(tidyverse)
  library(LaplacesDemon)
  library(semTools)
  library(psych)
  library(tictoc)
  # specify simulation conditions
  N_SET <- 10
  TOTREP <- 10000
  numcat <- c(2, 5)
  dist <- c(1, 2, 3, 4, 5) # 1 normal, 2 skewed, 3 platykurtic, 4 leptokurtic, 5 severe
  rep_sets <- start_rep:end_rep
  rep_per_set <- 1:(TOTREP/N_SET)
  conditions <- tidyr::crossing(numcat, dist)
  colnames(conditions) <- c("numcat", "dist")
  condition_numbers <- start_con:end_con
  name <- "study3"
  #========================================================================
  # Generate
  #========================================================================
  generate <- function(conditions, condition_number, rep_set, rep) {
    library(LaplacesDemon)
    # seed and variable names
    set.seed(100000*condition_number + 10000 * rep_set + rep)
    numcat <- as.integer(conditions[condition_number, 1])
    dist <- as.integer(conditions[condition_number, 2])
    # Parameters
    n <- 10000
    skew <- 0
    kurt <- 0
    if (dist == 2) {
      skew <- 2
    } else if (dist == 3) {
      kurt <- -1.2
    } else if (dist == 4) {
      kurt <- 7
    } else if (dist == 5) {
      skew <- 3
      kurt <- 21
    }
    theta <- semTools::mvrnonnorm(n, c(0,0), matrix(c(1, 0, 0, 1), 2, 2),
                                  skewness = c(skew, 0),
                                  kurtosis = c(kurt, 0))[, 1]
    alpha <- runif(1, min = .6, max = 1.4)
    if (numcat == 2) {
      beta <- runif(1, -1.3, 1.3)
    } else {
      beta <- sort(runif(4, -2, 2))
      beta[1] <- beta[1] - .2
      beta[2] <- beta[2] - .1
      beta[3] <- beta[3] + .1
      beta[4] <- beta[4] + .2
    }
    # Score generated by the FA model
    lambda <- alpha / sqrt(1 + alpha ^ 2)
    psi <- sqrt(1 - lambda^2)
    threshold <- beta / sqrt(1 + alpha ^ 2)
    continuous <- lambda * theta + rnorm(n, sd = psi)
    continuousp <- lambda * theta + rnorm(n, sd = psi)
    fa <- fap <- vector("double", n)
    for (i in 1:n) {
      if (numcat == 2) {
        fa[i] <- ifelse(continuous[i] < threshold, 0, 1)
      } else {
        if (continuous[i] < threshold[1]) {
          fa[i] <- 0
        } else if (continuous[i] < threshold[2]) {
          fa[i] <- 1
        } else if (continuous[i] < threshold[3]) {
          fa[i] <- 2
        } else if (continuous[i] < threshold[4]) {
          fa[i] <- 3
        } else {
          fa[i] <- 4
        }
      }
    }
    for (i in 1:n) { # parallel score
      if (numcat == 2) {
        fap[i] <- ifelse(continuousp[i] < threshold, 0, 1)
      } else {
        if (continuousp[i] < threshold[1]) {
          fap[i] <- 0
        } else if (continuousp[i] < threshold[2]) {
          fap[i] <- 1
        } else if (continuousp[i] < threshold[3]) {
          fap[i] <- 2
        } else if (continuousp[i] < threshold[4]) {
          fap[i] <- 3
        } else {
          fap[i] <- 4
        }
      }
    }
    # Score generated by IRT models (logistic and normal ogive)
    D <- seq(from = 1.65, to = 1.75, by = .01)
    if (numcat == 2) {
      p_l <- matrix(vector("double", n * length(D)), nrow = n, ncol = length(D))
    } else {
      p_l <- array(vector("double", n * (numcat - 1) * length(D)),
                   dim = c(n, numcat - 1, length(D)))
    }
    p_norm <- matrix(vector("double", n * (numcat - 1)), n, numcat - 1)
    l1 <- l2 <- l3 <- l4 <- l5 <- l6 <- l7 <- l8 <- l9 <- l10 <- vector("double", n)
    l11 <-  vector("double", n)
    l1p <- l2p <- l3p <- l4p <- l5p <- l6p <- l7p <- l8p <- l9p <- l10p <- vector("double", n)
    l11p <- vector("double", n)
    norm <- normp <-  vector("double", n)
    if (numcat == 2) {
      among <- c(0, 1)
      for (i in 1:n) {
        for (j in 1:length(D)) {
          p_l[i, j] <- invlogit(D[j] * (alpha * theta[i] - beta))
        }
        p_norm[i] <- pnorm(alpha * theta[i] - beta)
        norm[i] <- sample(among, size = 1, replace = TRUE,
                          prob = c(1 - p_norm[i], p_norm[i]))
        normp[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                           prob = c(1 - p_norm[i], p_norm[i]))
        l1[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 1], p_l[i, 1]))
        l1p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 1], p_l[i, 1]))
        l2[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 2], p_l[i, 2]))
        l2p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 2], p_l[i, 2]))
        l3[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 3], p_l[i, 3]))
        l3p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 3], p_l[i, 3]))
        l4[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 4], p_l[i, 4]))
        l4p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 4], p_l[i, 4]))
        l5[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 5], p_l[i, 5]))
        l5p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 5], p_l[i, 5]))
        l6[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 6], p_l[i, 6]))
        l6p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 6], p_l[i, 6]))
        l7[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 7], p_l[i, 7]))
        l7p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 7], p_l[i, 7]))
        l8[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 8], p_l[i, 8]))
        l8p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 8], p_l[i, 8]))
        l9[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 9], p_l[i, 9]))
        l9p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                         prob = c(1 - p_l[i, 9], p_l[i, 9]))
        l10[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1 - p_l[i, 10], p_l[i, 10]))
        l10p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                          prob = c(1 - p_l[i, 10], p_l[i, 10]))
        l11[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1 - p_l[i, 11], p_l[i, 11]))
        l11p[i] <- sample(among, size = 1, replace = TRUE, # parallel score
                          prob = c(1 - p_l[i, 11], p_l[i, 11]))
      }
    } else {
      among <- c(0, 1, 2, 3, 4)
      for (i in 1:n) {
        for (j in 1:(numcat - 1)) {
          for (k in 1:length(D)) {
            p_l[i, j, k] <- invlogit(D[k] * (alpha * theta[i] - beta[j]))
          }
          p_norm[i, j] <- pnorm(alpha * theta[i] - beta[j])
        }
      }
      for (i in 1:n) {
        norm[i] <- sample(among, size = 1, replace = TRUE,
                          prob = c(1- p_norm[i, 1],
                                   p_norm[i, 1] - p_norm[i, 2],
                                   p_norm[i, 2] - p_norm[i, 3],
                                   p_norm[i, 3] - p_norm[i, 4],
                                   p_norm[i, 4]))
        normp[i] <- sample(among, size = 1, replace = TRUE,
                           prob = c(1- p_norm[i, 1],
                                    p_norm[i, 1] - p_norm[i, 2],
                                    p_norm[i, 2] - p_norm[i, 3],
                                    p_norm[i, 3] - p_norm[i, 4],
                                    p_norm[i, 4]))
        l1[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 1],
                                 p_l[i, 1, 1] - p_l[i, 2, 1],
                                 p_l[i, 2, 1] - p_l[i, 3, 1],
                                 p_l[i, 3, 1] - p_l[i, 4, 1],
                                 p_l[i, 4, 1]))
        l1p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 1],
                                  p_l[i, 1, 1] - p_l[i, 2, 1],
                                  p_l[i, 2, 1] - p_l[i, 3, 1],
                                  p_l[i, 3, 1] - p_l[i, 4, 1],
                                  p_l[i, 4, 1]))
        l2[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 2],
                                 p_l[i, 1, 2] - p_l[i, 2, 2],
                                 p_l[i, 2, 2] - p_l[i, 3, 2],
                                 p_l[i, 3, 2] - p_l[i, 4, 2],
                                 p_l[i, 4, 2]))
        l2p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 2],
                                  p_l[i, 1, 2] - p_l[i, 2, 2],
                                  p_l[i, 2, 2] - p_l[i, 3, 2],
                                  p_l[i, 3, 2] - p_l[i, 4, 2],
                                  p_l[i, 4, 2]))
        l3[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 3],
                                 p_l[i, 1, 3] - p_l[i, 2, 3],
                                 p_l[i, 2, 3] - p_l[i, 3, 3],
                                 p_l[i, 3, 3] - p_l[i, 4, 3],
                                 p_l[i, 4, 3]))
        l3p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 3],
                                  p_l[i, 1, 3] - p_l[i, 2, 3],
                                  p_l[i, 2, 3] - p_l[i, 3, 3],
                                  p_l[i, 3, 3] - p_l[i, 4, 3],
                                  p_l[i, 4, 3]))
        l4[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 4],
                                 p_l[i, 1, 4] - p_l[i, 2, 4],
                                 p_l[i, 2, 4] - p_l[i, 3, 4],
                                 p_l[i, 3, 4] - p_l[i, 4, 4],
                                 p_l[i, 4, 4]))
        l4p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 4],
                                  p_l[i, 1, 4] - p_l[i, 2, 4],
                                  p_l[i, 2, 4] - p_l[i, 3, 4],
                                  p_l[i, 3, 4] - p_l[i, 4, 4],
                                  p_l[i, 4, 4]))
        l5[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 5],
                                 p_l[i, 1, 5] - p_l[i, 2, 5],
                                 p_l[i, 2, 5] - p_l[i, 3, 5],
                                 p_l[i, 3, 5] - p_l[i, 4, 5],
                                 p_l[i, 4, 5]))
        l5p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 5],
                                  p_l[i, 1, 5] - p_l[i, 2, 5],
                                  p_l[i, 2, 5] - p_l[i, 3, 5],
                                  p_l[i, 3, 5] - p_l[i, 4, 5],
                                  p_l[i, 4, 5]))
        l6[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 6],
                                 p_l[i, 1, 6] - p_l[i, 2, 6],
                                 p_l[i, 2, 6] - p_l[i, 3, 6],
                                 p_l[i, 3, 6] - p_l[i, 4, 6],
                                 p_l[i, 4, 6]))
        l6p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 6],
                                  p_l[i, 1, 6] - p_l[i, 2, 6],
                                  p_l[i, 2, 6] - p_l[i, 3, 6],
                                  p_l[i, 3, 6] - p_l[i, 4, 6],
                                  p_l[i, 4, 6]))
        l7[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 7],
                                 p_l[i, 1, 7] - p_l[i, 2, 7],
                                 p_l[i, 2, 7] - p_l[i, 3, 7],
                                 p_l[i, 3, 7] - p_l[i, 4, 7],
                                 p_l[i, 4, 7]))
        l7p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 7],
                                  p_l[i, 1, 7] - p_l[i, 2, 7],
                                  p_l[i, 2, 7] - p_l[i, 3, 7],
                                  p_l[i, 3, 7] - p_l[i, 4, 7],
                                  p_l[i, 4, 7]))
        l8[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 8],
                                 p_l[i, 1, 8] - p_l[i, 2, 8],
                                 p_l[i, 2, 8] - p_l[i, 3, 8],
                                 p_l[i, 3, 8] - p_l[i, 4, 8],
                                 p_l[i, 4, 8]))
        l8p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 8],
                                  p_l[i, 1, 8] - p_l[i, 2, 8],
                                  p_l[i, 2, 8] - p_l[i, 3, 8],
                                  p_l[i, 3, 8] - p_l[i, 4, 8],
                                  p_l[i, 4, 8]))
        l9[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 9],
                                 p_l[i, 1, 9] - p_l[i, 2, 9],
                                 p_l[i, 2, 9] - p_l[i, 3, 9],
                                 p_l[i, 3, 9] - p_l[i, 4, 9],
                                 p_l[i, 4, 9]))
        l9p[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 9],
                                  p_l[i, 1, 9] - p_l[i, 2, 9],
                                  p_l[i, 2, 9] - p_l[i, 3, 9],
                                  p_l[i, 3, 9] - p_l[i, 4, 9],
                                  p_l[i, 4, 9]))
        l10[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 10],
                                  p_l[i, 1, 10] - p_l[i, 2, 10],
                                  p_l[i, 2, 10] - p_l[i, 3, 10],
                                  p_l[i, 3, 10] - p_l[i, 4, 10],
                                  p_l[i, 4, 10]))
        l10p[i] <- sample(among, size = 1, replace = TRUE,
                          prob = c(1- p_l[i, 1, 10],
                                   p_l[i, 1, 10] - p_l[i, 2, 10],
                                   p_l[i, 2, 10] - p_l[i, 3, 10],
                                   p_l[i, 3, 10] - p_l[i, 4, 10],
                                   p_l[i, 4, 10]))
        l11[i] <- sample(among, size = 1, replace = TRUE,
                         prob = c(1- p_l[i, 1, 11],
                                  p_l[i, 1, 11] - p_l[i, 2, 11],
                                  p_l[i, 2, 11] - p_l[i, 3, 11],
                                  p_l[i, 3, 11] - p_l[i, 4, 11],
                                  p_l[i, 4, 11]))
        l11p[i] <- sample(among, size = 1, replace = TRUE,
                          prob = c(1- p_l[i, 1, 11],
                                   p_l[i, 1, 11] - p_l[i, 2, 11],
                                   p_l[i, 2, 11] - p_l[i, 3, 11],
                                   p_l[i, 3, 11] - p_l[i, 4, 11],
                                   p_l[i, 4, 11]))
      }
    }
    out <- tibble::tibble(fa, fap, norm, normp, l1, l1p, l2, l2p, l3, l3p, l4, l4p,
                          l5, l5p, l6, l6p, l7, l7p, l8, l8p, l9, l9p, l10, l10p,
                          l11, l11p)
    return(out)
  }
  #========================================================================
  # Analyze
  #========================================================================
  analyze <- function(conditions, condition_number, rep_set, rep, data) {
    library(dgof)
    numcat <- as.integer(conditions[condition_number, 1])
    dist <- as.integer(conditions[condition_number, 2])
    fa <- data$fa
    fap <- data$fap
    norm <- data$norm
    normp <- data$normp
    l1 <- data$l1
    l1p <- data$l1p
    l2 <- data$l2
    l2p <- data$l2p
    l3 <- data$l3
    l3p <- data$l3p
    l4 <- data$l4
    l4p <- data$l4p
    l5 <- data$l5
    l5p <- data$l5p
    l6 <- data$l6
    l6p <- data$l6p
    l7 <- data$l7
    l7p <- data$l7p
    l8 <- data$l8
    l8p <- data$l8p
    l9 <- data$l9
    l9p <- data$l9p
    l10 <- data$l10
    l10p <- data$l10p
    l11 <- data$l11
    l11p <- data$l11p
    # Kolmogorov Smirnov test
    ff <- ks.test(fa, fap)$statistic
    nn <- ks.test(norm, normp)$statistic
    fn <- ks.test(fa, norm)$statistic
    lp1 <- ks.test(l1, l1p)$statistic
    lp2 <- ks.test(l2, l2p)$statistic
    lp3 <- ks.test(l3, l3p)$statistic
    lp4 <- ks.test(l4, l4p)$statistic
    lp5 <- ks.test(l5, l5p)$statistic
    lp6 <- ks.test(l6, l6p)$statistic
    lp7 <- ks.test(l7, l7p)$statistic
    lp8 <- ks.test(l8, l8p)$statistic
    lp9 <- ks.test(l9, l9p)$statistic
    lp10 <- ks.test(l10, l10p)$statistic
    lp11 <- ks.test(l11, l11p)$statistic
    fl1 <- ks.test(fa, l1)$statistic
    fl2 <- ks.test(fa, l2)$statistic
    fl3 <- ks.test(fa, l3)$statistic
    fl4 <- ks.test(fa, l4)$statistic
    fl5 <- ks.test(fa, l5)$statistic
    fl6 <- ks.test(fa, l6)$statistic
    fl7 <- ks.test(fa, l7)$statistic
    fl8 <- ks.test(fa, l8)$statistic
    fl9 <- ks.test(fa, l9)$statistic
    fl10 <- ks.test(fa, l10)$statistic
    fl11 <- ks.test(fa, l11)$statistic
    ln1 <- ks.test(norm, l1)$statistic
    ln2 <- ks.test(norm, l2)$statistic
    ln3 <- ks.test(norm, l3)$statistic
    ln4 <- ks.test(norm, l4)$statistic
    ln5 <- ks.test(norm, l5)$statistic
    ln6 <- ks.test(norm, l6)$statistic
    ln7 <- ks.test(norm, l7)$statistic
    ln8 <- ks.test(norm, l8)$statistic
    ln9 <- ks.test(norm, l9)$statistic
    ln10 <- ks.test(norm, l10)$statistic
    ln11 <- ks.test(norm, l11)$statistic
    out <- tibble::tibble(numcat, dist, ff, nn, fn,
                          lp1, lp2, lp3, lp4, lp5, lp6, lp7, lp8, lp9, lp10, lp11,
                          fl1, fl2, fl3, fl4, fl5, fl6, fl7, fl8, fl9, fl10, fl11,
                          ln1, ln2, ln3, ln4, ln5, ln6, ln7, ln8, ln9, ln10, ln11)
    return(out)
  }
  #========================================================================
  # Loop
  #========================================================================
  for (condition_number in condition_numbers) {
    condition <- conditions[condition_number, ]
    print(condition)
    for (rep_set in rep_sets) {
      tictoc::tic()
      print(paste("Starting condition number", condition_number, "rep", rep_set))
      print(condition)
      filename <- paste0(name, "-", condition_number, "-", rep_set, ".csv")
      if (!file.exists(filename)) {
        for (rep in rep_per_set) {
          cat(name, ": ", condition_number, "rep set: ", rep_set, "rep: ", rep)
          data <- generate(conditions, condition_number, rep_set, rep)
          if (rep == 1) {
            temp <- analyze(conditions, condition_number, rep_set, rep, data)
          } else {
            temp <- rbind(temp,
                          analyze(conditions, condition_number, rep_set, rep, data))
          }
        } # end of for (rep in rep_per_set)
        # 3 duplicates, leaving only one
        out <- temp
        readr::write_csv(data.frame(out), file = filename)
        print(out)
        tictoc::toc()
      } # end of if (!file.exists(filename))
    } # end of  for (rep_set in rep_sets)
  } # end of for (condition_number in condition_numbers)
  #========================================================================
  # summarize
  #========================================================================
  library(tidyverse)
  end <- 10
  name <- "study3"
  for (i in 1:end) {
    if (i == 1) {
      dat <- 1:20 %>%
        purrr::map(~ read_csv(file = paste0(name, "-", i, "-", .x, ".csv"))) %>%
        dplyr::bind_rows()
    } else {
      tmp <- 1:20 %>%
        purrr::map(~ read_csv(file = paste0(name, "-", i, "-", .x, ".csv"))) %>%
        dplyr::bind_rows()
      dat <- dplyr::bind_rows(dat, tmp)
    }
  }
  stats <- dat %>% select(ff:ln11) %>% summarise_all(mean)
  write_csv(stats, "stats.csv")
  dat <- dat %>% mutate(fn = ifelse(fn>nn, .5, ifelse(fn<nn, -.5, 0)) + ifelse(fn>ff, .5, ifelse(fn<ff, -.5, 0))) %>% mutate(f1 = ifelse(fl1>ff, .5, ifelse(fl1<ff, -.5, 0)) + ifelse(fl1>lp1, .5, ifelse(fl1<lp1, -.5, 0)))
  dat <- dat %>% mutate(f2 = ifelse(fl2>ff, .5, ifelse(fl2<ff, -.5, 0)) + ifelse(fl2>lp2, .5, ifelse(fl2<lp2, -.5, 0)))
  dat <- dat %>% mutate(f3 = ifelse(fl3>ff, .5, ifelse(fl3<ff, -.5, 0)) + ifelse(fl3>lp3, .5, ifelse(fl3<lp3, -.5, 0)))
  dat <- dat %>% mutate(f4 = ifelse(fl4>ff, .5, ifelse(fl4<ff, -.5, 0)) + ifelse(fl4>lp4, .5, ifelse(fl4<lp4, -.5, 0)))
  dat <- dat %>% mutate(f5 = ifelse(fl5>ff, .5, ifelse(fl5<ff, -.5, 0)) + ifelse(fl5>lp5, .5, ifelse(fl5<lp5, -.5, 0)))
  dat <- dat %>% mutate(f6 = ifelse(fl6>ff, .5, ifelse(fl6<ff, -.5, 0)) + ifelse(fl6>lp6, .5, ifelse(fl6<lp6, -.5, 0)))
  dat <- dat %>% mutate(f7 = ifelse(fl7>ff, .5, ifelse(fl7<ff, -.5, 0)) + ifelse(fl7>lp7, .5, ifelse(fl7<lp7, -.5, 0)))
  dat <- dat %>% mutate(f8 = ifelse(fl8>ff, .5, ifelse(fl8<ff, -.5, 0)) + ifelse(fl8>lp8, .5, ifelse(fl8<lp8, -.5, 0)))
  dat <- dat %>% mutate(f9 = ifelse(fl9>ff, .5, ifelse(fl9<ff, -.5, 0)) + ifelse(fl9>lp9, .5, ifelse(fl9<lp9, -.5, 0)))
  dat <- dat %>% mutate(f10 = ifelse(fl10>ff, .5, ifelse(fl10<ff, -.5, 0)) + ifelse(fl10>lp10, .5, ifelse(fl10<lp10, -.5, 0)))
  dat <- dat %>% mutate(f11 = ifelse(fl11>ff, .5, ifelse(fl11<ff, -.5, 0)) + ifelse(fl11>lp11, .5, ifelse(fl11<lp11, -.5, 0)))
  dat <- dat %>% mutate(n1 = ifelse(ln1>nn, .5, ifelse(ln1<nn, -.5, 0)) + ifelse(ln1>lp1, .5, ifelse(ln1<lp1, -.5, 0)))
  dat <- dat %>% mutate(n2 = ifelse(ln2>nn, .5, ifelse(ln2<nn, -.5, 0)) + ifelse(ln2>lp2, .5, ifelse(ln2<lp2, -.5, 0)))
  dat <- dat %>% mutate(n3 = ifelse(ln3>nn, .5, ifelse(ln3<nn, -.5, 0)) + ifelse(ln3>lp3, .5, ifelse(ln3<lp3, -.5, 0)))
  dat <- dat %>% mutate(n4 = ifelse(ln4>nn, .5, ifelse(ln4<nn, -.5, 0)) + ifelse(ln4>lp4, .5, ifelse(ln4<lp4, -.5, 0)))
  dat <- dat %>% mutate(n5 = ifelse(ln5>nn, .5, ifelse(ln5<nn, -.5, 0)) + ifelse(ln5>lp5, .5, ifelse(ln5<lp5, -.5, 0)))
  dat <- dat %>% mutate(n6 = ifelse(ln6>nn, .5, ifelse(ln6<nn, -.5, 0)) + ifelse(ln6>lp6, .5, ifelse(ln6<lp6, -.5, 0)))
  dat <- dat %>% mutate(n7 = ifelse(ln7>nn, .5, ifelse(ln7<nn, -.5, 0)) + ifelse(ln7>lp7, .5, ifelse(ln7<lp7, -.5, 0)))
  dat <- dat %>% mutate(n8 = ifelse(ln8>nn, .5, ifelse(ln8<nn, -.5, 0)) + ifelse(ln8>lp8, .5, ifelse(ln8<lp8, -.5, 0)))
  dat <- dat %>% mutate(n9 = ifelse(ln9>nn, .5, ifelse(ln9<nn, -.5, 0)) + ifelse(ln9>lp9, .5, ifelse(ln9<lp9, -.5, 0)))
  dat <- dat %>% mutate(n10 = ifelse(ln10>nn, .5, ifelse(ln10<nn, -.5, 0)) + ifelse(ln10>lp10, .5, ifelse(ln10<lp10, -.5, 0)))
  dat <- dat %>% mutate(n11 = ifelse(ln11>nn, .5, ifelse(ln11<nn, -.5, 0)) + ifelse(ln11>lp11, .5, ifelse(ln11<lp11, -.5, 0)))
  out <- dat %>% dplyr::group_by(numcat, dist) %>% select(fn, f6, n3:n11) %>%  summarize_all(mean)
  write.csv(out, "study3out.csv")
  return(out)
}
