study4 <- function(start_con = 1, end_con = 75) {
  library(tidyverse)
  library(LaplacesDemon)
  library(semTools)
  library(psych)
  library(ggplot2)
  library(viridis)
  library(lemon)
  # specify simulation conditions
  alpha <- c(.6, 1, 1.4)
  dist <- c(1, 2, 3, 4, 5) # 1 normal, 2 skewed, 3 platykurtic, 4 leptokurtic, 5 severe
  beta <- c(-1, -.5, 0, .5, 1)
  conditions <- tidyr::crossing( dist, alpha, beta)
  colnames(conditions) <- c("dist", "alpha", "beta")
  condition_numbers <- start_con:end_con
  name <- "study4-"
  #========================================================================
  # Generate
  #========================================================================
  generate <- function(conditions, condition_number) {
    library(LaplacesDemon)
    # seed and variable names
    set.seed(100000*condition_number)
    numcat <- 2
    dist <- as.integer(conditions[condition_number, 1])
    alpha <- as.double(conditions[condition_number, 2])
    beta <- as.double(conditions[condition_number, 3])
    # Parameters
    n <- 10^6
    skew <- 0
    kurt <- 0
    if (dist == 2) {
      skew <- 2
    } else if (dist == 3) {
      kurt <- -1.2
    } else if (dist == 4) {
      kurt <- 7
    } else if (dist == 5) {
      skew <- 3
      kurt <- 21
    }
    theta <- semTools::mvrnonnorm(n, c(0,0), matrix(c(1, 0, 0, 1), 2, 2),
                                  skewness = c(skew, 0),
                                  kurtosis = c(kurt, 0))[, 1]
    # Score generated by the FA model
    lambda <- alpha / sqrt(1 + alpha ^ 2)
    psi <- sqrt(1 - lambda^2)
    threshold <- beta / sqrt(1 + alpha ^ 2)
    continuous <- lambda * theta + rnorm(n, sd = psi)
    fa <- fap <- vector("double", n)
    for (i in 1:n) {
      if (numcat == 2) {
        fa[i] <- ifelse(continuous[i] < threshold, 0, 1)
      } else {
        if (continuous[i] < threshold[1]) {
          fa[i] <- 0
        } else if (continuous[i] < threshold[2]) {
          fa[i] <- 1
        } else if (continuous[i] < threshold[3]) {
          fa[i] <- 2
        } else if (continuous[i] < threshold[4]) {
          fa[i] <- 3
        } else {
          fa[i] <- 4
        }
      }
    }
    # Score generated by IRT models (logistic and normal ogive)
    D <- c(1.68, 1.71, 1.74)
    if (numcat == 2) {
      p_l <- matrix(vector("double", n * length(D)), nrow = n, ncol = length(D))
    } else {
      p_l <- array(vector("double", n * (numcat - 1) * length(D)),
                   dim = c(n, numcat - 1, length(D)))
    }
    p_norm <- matrix(vector("double", n * (numcat - 1)), n, numcat - 1)
    l1 <- l2 <- l3 <- vector("double", n)
    norm <- vector("double", n)
    if (numcat == 2) {
      among <- c(0, 1)
      for (i in 1:n) {
        for (j in 1:length(D)) {
          p_l[i, j] <- invlogit(D[j] * (alpha * theta[i] - beta))
        }
        p_norm[i] <- pnorm(alpha * theta[i] - beta)
        norm[i] <- sample(among, size = 1, replace = TRUE,
                          prob = c(1 - p_norm[i], p_norm[i]))
        l1[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 1], p_l[i, 1]))
        l2[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 2], p_l[i, 2]))
        l3[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1 - p_l[i, 3], p_l[i, 3]))
      }
    } else {
      among <- c(0, 1, 2, 3, 4)
      for (i in 1:n) {
        for (j in 1:(numcat - 1)) {
          for (k in 1:length(D)) {
            p_l[i, j, k] <- invlogit(D[k] * (alpha * theta[i] - beta[j]))
          }
          p_norm[i, j] <- pnorm(alpha * theta[i] - beta[j])
        }
      }
      for (i in 1:n) {
        norm[i] <- sample(among, size = 1, replace = TRUE,
                          prob = c(1- p_norm[i, 1],
                                   p_norm[i, 1] - p_norm[i, 2],
                                   p_norm[i, 2] - p_norm[i, 3],
                                   p_norm[i, 3] - p_norm[i, 4],
                                   p_norm[i, 4]))
        l1[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 1],
                                 p_l[i, 1, 1] - p_l[i, 2, 1],
                                 p_l[i, 2, 1] - p_l[i, 3, 1],
                                 p_l[i, 3, 1] - p_l[i, 4, 1],
                                 p_l[i, 4, 1]))
        l2[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 2],
                                 p_l[i, 1, 2] - p_l[i, 2, 2],
                                 p_l[i, 2, 2] - p_l[i, 3, 2],
                                 p_l[i, 3, 2] - p_l[i, 4, 2],
                                 p_l[i, 4, 2]))
        l3[i] <- sample(among, size = 1, replace = TRUE,
                        prob = c(1- p_l[i, 1, 3],
                                 p_l[i, 1, 3] - p_l[i, 2, 3],
                                 p_l[i, 2, 3] - p_l[i, 3, 3],
                                 p_l[i, 3, 3] - p_l[i, 4, 3],
                                 p_l[i, 4, 3]))
      }
    }
    out <- tibble::tibble(fa, norm, l1, l2, l3)
    return(out)
  }
  #========================================================================
  # Analyze
  #========================================================================
  analyzefreq <- function(conditions, condition_number, data) {
    numcat <- 2
    dist <- as.integer(conditions[condition_number, 1])
    alpha <- as.double(conditions[condition_number, 2])
    beta <- as.double(conditions[condition_number, 3])
    if (numcat == 2) {
      f0 <- table(data[, 1])[1]
      f1 <- table(data[, 1])[2]
      f2 <- f3 <- f4 <- NA
      n0 <- table(data[, 2])[1]
      n1 <- table(data[, 2])[2]
      n2 <- n3 <- n4 <- NA
      l10 <- table(data[, 3])[1]
      l11 <- table(data[, 3])[2]
      l12 <- l13 <- l14 <- NA
      l20 <- table(data[, 4])[1]
      l21 <- table(data[, 4])[2]
      l22 <- l23 <- l24 <- NA
      l30 <- table(data[, 5])[1]
      l31 <- table(data[, 5])[2]
      l32 <- l33 <- l34 <- NA
    } else {
      f0 <- table(data[, 1])[1]
      f1 <- table(data[, 1])[2]
      f2 <- table(data[, 1])[3]
      f3 <- table(data[, 1])[4]
      f4 <- table(data[, 1])[5]
      n0 <- table(data[, 2])[1]
      n1 <- table(data[, 2])[2]
      n2 <- table(data[, 2])[3]
      n3 <- table(data[, 2])[4]
      n4 <- table(data[, 2])[5]
      l10 <- table(data[, 3])[1]
      l11 <- table(data[, 3])[2]
      l12 <- table(data[, 3])[3]
      l13 <- table(data[, 3])[4]
      l14 <- table(data[, 3])[5]
      l20 <- table(data[, 4])[1]
      l21 <- table(data[, 4])[2]
      l22 <- table(data[, 4])[3]
      l23 <- table(data[, 4])[4]
      l24 <- table(data[, 4])[5]
      l30 <- table(data[, 5])[1]
      l31 <- table(data[, 5])[2]
      l32 <- table(data[, 5])[3]
      l33 <- table(data[, 5])[4]
      l34 <- table(data[, 5])[5]
    }
    out <- tibble::tibble(dist, alpha, beta,
                          f0, f1, f2, f3, f4, n0, n1, n2, n3, n4,
                          l10, l11, l12, l13, l14, l20, l21, l22, l23, l24,
                          l30, l31, l32, l33, l34)
    return(out)
  }
  #========================================================================
  # Loop
  #========================================================================
  for (condition_number in condition_numbers) {
    condition <- conditions[condition_number, ]
    print(condition)
    filename <- paste0(name, condition_number, ".csv")
    print(condition)
    data <- generate(conditions, condition_number)
    if (condition_number == 1) {
      dat <- analyzefreq(conditions, condition_number, data)
    } else {
      dat <- rbind(dat, analyzefreq(conditions, condition_number, data))
    }
  } # end of for (condition_number in condition_numbers)
  #========================================================================
  # Graph
  #========================================================================
  dat <- dat %>% mutate(fn = f1 - n1) %>%
    mutate(l1n = l11 - n1) %>%
    mutate(l2n = l21 - n1) %>%
    mutate(l3n = l31 - n1)
  dat <- dat %>% select(dist, alpha, beta, fn, l1n, l2n, l3n)
  dat <- dat %>% mutate_at(vars(fn, l1n, l2n, l3n), ~.x/10^6 )
  dat <- dat %>% filter(alpha == 1.4)
  dat <- dat %>% pivot_longer(cols = fn:l3n, names_to = 'models', values_to = 'dif')
  dat <- dat %>% rename(location = beta)
  for (i  in 1:nrow(dat)) {
    dat$models[i] <- switch(dat$models[i], "fn" = "Factor Analysis",
                            "l1n" = "Logistic D = 1.68",
                            "l2n" = "Logistic D = 1.71",
                            "l3n" = "Logistic D = 1.74")
  }
  dat$dist <- as.character(dat$dist)
  dat$location <- as.character(dat$location)
  dat$location <- factor(dat$location, levels = c("-1", "-0.5", "0", "0.5", "1"))
  model_label <- c(fn = "FA", l1n = "Logistic 1.68", l2n = "Logistic 1.71", l3n = "Logistic 1.74" )
  dist_label <- c("1" = "normal", "2" = "skewed", "3" = "platykurtic", "4" = "leptokurtic", "5" = "severe")
  location_label <- c("-1" = "location(beta): -1", "-.6" = "location(beta): -.6",
                      "0" = "location(beta): 0", ".6" = "location(beta): .6",
                      "1" = "location(beta): 1")
  model_location <- ggplot(dat, aes(y = dif, x = location)) + geom_col() +
    scale_fill_viridis(option = 'inferno',discrete = TRUE) +
    xlab("location or difficulty parameters (beta)") +
    ylab("Difference between each model and the normal ogive model") +
    theme_classic() +
    scale_y_continuous(breaks = c(-.005, 0, .005))+
    theme(panel.border = element_blank(),
          strip.background =element_blank(),
          strip.text = element_text(size = 13),
          axis.text.x = element_text(size = 13),
          axis.title.x = element_text(size = 13),
          strip.placement = 'outside') +
    facet_grid(c("dist", "models"),
               labeller = labeller(dist = dist_label)
    )
  model_location
}
